[package]
name = "spm-linear"
edition.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
spm-codec-dense = { path = "../../../format/crates/spm-codec-dense" }
spm-layout = { path = "../../../format/crates/spm-layout" }
spm-stream = { path = "../../../stream/crates/spm-stream" }
spm-stream-groups = { path = "../../../stream/crates/spm-stream-groups" }

[dev-dependencies]
spm-file = { path = "../../../format/crates/spm-file" }
spm-stream-mem = { path = "../../../stream/crates/spm-stream-mem" }
spm-walk = { path = "../../../format/crates/spm-walk" }
