"use strict";
(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;else root.EmuArchitectures=api;})(typeof globalThis==="object"?globalThis:this,function(){
  const nodes={hdd:[55,95,"HDD","bulk / cold"],ssd:[55,205,"NVMe SSD","indexed experts"],pmem:[55,315,"PMEM","persistent tier"],cpu:[330,150,"CPU","router + fallback"],ram:[330,300,"SYSTEM RAM","cache / staging"],pio:[330,450,"MCU / PIO","control only"],fpga:[610,150,"FPGA","decode + MAC"],gpu:[890,150,"GPU","dense + attention"],vram:[890,315,"VRAM","KV + hot weights"],client:[610,450,"REQUESTS","prompt / tokens"]};
  const edge=(from,to,kind,label)=>({from,to,kind,label});
  const scenarios={
    baseline:{name:"CPU + DRAM baseline",state:"PARTLY MEASURED",thesis:"Simplest control path. It is the comparison to beat: cached packed weights already feed scalar CPU compute faster than storage in the current B1 experiment.",active:["hdd","ssd","cpu","ram","client"],edges:[edge("hdd","ram","weights","cold weights"),edge("ssd","ram","weights","expert fetch"),edge("ram","cpu","weights","packed weights"),edge("client","cpu","activation","prompt / activations"),edge("cpu","ram","kv","KV read + write"),edge("cpu","client","activation","tokens")]},
    gpu:{name:"GPU with staged experts",state:"PROPOSED / NOT YET MEASURED",thesis:"Keep attention and KV in VRAM; stage routed expert weights through pinned RAM. This helps only when PCIe transfers overlap useful GPU work and the active expert set does not fill VRAM.",active:["ssd","cpu","ram","gpu","vram","client"],edges:[edge("ssd","ram","weights","selected weights"),edge("ram","vram","weights","PCIe staging"),edge("client","gpu","activation","prompt"),edge("gpu","vram","kv","KV + hot state"),edge("gpu","cpu","control","expert IDs"),edge("gpu","client","activation","tokens")]},
    pmem:{name:"PMEM capacity tier",state:"PROPOSED / HARDWARE INVENTORY PENDING",thesis:"Use Optane PMEM as a larger byte-addressable expert store behind DRAM. Capacity may improve, but NUMA placement and App Direct bandwidth must be measured on each available server.",active:["pmem","cpu","ram","gpu","vram","client"],edges:[edge("pmem","ram","weights","expert pages"),edge("ram","cpu","weights","CPU expert"),edge("ram","vram","weights","GPU stage"),edge("client","gpu","activation","prompt / activations"),edge("gpu","vram","kv","KV cache"),edge("gpu","cpu","control","routes")]},
    fpga:{name:"FPGA serial expert coprocessor",state:"SIMULATED DATAPATH / PHYSICAL I/O UNMEASURED",thesis:"Stream packed selected experts through a bounded decoder/MAC pipeline while requests share each pass. The decisive experiment is whether storage, link, and arithmetic overlap at a useful sustained rate.",active:["hdd","ssd","ram","fpga","gpu","vram","client"],edges:[edge("hdd","ram","weights","sequential weights"),edge("ssd","ram","weights","selected experts"),edge("ram","fpga","weights","packed blocks"),edge("gpu","fpga","activation","routed activations"),edge("fpga","gpu","activation","expert outputs"),edge("gpu","vram","kv","KV stays hot"),edge("client","gpu","activation","prompt / tokens")]},
    pio:{name:"MCU / PIO transport helper",state:"PROPOSED CONTROL EXPERIMENT",thesis:"PIO can frame DMA, apply backpressure, timestamp transfers, or select streams. It cannot provide enough memory bandwidth or MAC throughput to replace CPU, GPU, or FPGA expert math.",active:["ssd","ram","pio","fpga","gpu","vram","client"],edges:[edge("ssd","ram","weights","weights"),edge("ram","fpga","weights","DMA payload"),edge("pio","ram","control","DMA control"),edge("pio","fpga","control","framing / ready"),edge("gpu","fpga","activation","activations"),edge("fpga","gpu","activation","outputs"),edge("gpu","vram","kv","KV cache"),edge("client","gpu","activation","requests")]}
  };return {nodes,scenarios};
});
