[package]
name = "spm-smol"
edition.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
spm-linear = { path = "../spm-linear" }
spm-ops = { path = "../spm-ops" }
spm-smol-ops = { path = "../spm-smol-ops" }
spm-stream = { path = "../../../stream/crates/spm-stream" }
spm-stream-groups = { path = "../../../stream/crates/spm-stream-groups" }

[dev-dependencies]
spm-smol-ops = { path = "../spm-smol-ops" }
spm-codec-dense = { path = "../../../format/crates/spm-codec-dense" }
spm-file = { path = "../../../format/crates/spm-file" }
spm-layout = { path = "../../../format/crates/spm-layout" }
spm-stream-file = { path = "../../../stream/crates/spm-stream-file" }
spm-stream-metrics = { path = "../../../stream/crates/spm-stream-metrics" }
spm-stream-mem = { path = "../../../stream/crates/spm-stream-mem" }

[[example]]
name = "smol-xcheck"
